name: Cashere
description: "A simple POS Application"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.4
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.19.0
  fl_chart: ^0.71.0
  csv: ^6.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10
  flutter_thermal_printer: ^1.2.1+1
  image_picker: ^1.1.2
  image: ^4.5.4
  esc_pos_utils_plus: ^2.0.4
  flutter_blue_plus: ^1.35.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon_cashere.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_cashere.png"
  adaptive_icon_background: "#ffffff" # (opsional)
  adaptive_icon_foreground: "assets/icon_cashere.png" # (opsional)